// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * k6 cloud execution example
 *
 * Covers: cloud options (cloud run), multi-region distribution,
 *         k6 cloud run and k6 cloud run --local-execution
 *
 * Run commands:
 *   k6 cloud login --token <YOUR_API_TOKEN>
 *   k6 cloud run k6/scripts/cloud-test.js           # remote execution
 *   k6 cloud run --local-execution k6/scripts/cloud-test.js  # hybrid
 *
 * The script itself is identical for both run modes.
 * --local-execution is a CLI flag only — it runs the test on your machine
 * but streams results to Grafana Cloud for storage and dashboarding.
 *
 * Get your projectID from app.k6.io → project settings.
 */
import http from 'k6/http';
import { check, sleep } from 'k6';

const BASE_URL = 'https://quickpizza.grafana.com';

export const options = {
  // ── Cloud-specific configuration ────────────────────────────────────────
  cloud: {
    projectID: 1234567, // replace with your project ID
    name: 'QuickPizza Cloud Load Test',

    // Optional: multi-region distribution (percentages must sum to 100)
    distribution: {
      'amazon:us:ashburn': { loadZone: 'amazon:us:ashburn', percent: 60 },
      'amazon:eu:dublin': { loadZone: 'amazon:eu:dublin', percent: 40 },
    },
  },

  // ── Load configuration (same as local) ──────────────────────────────────
  scenarios: {
    cloud_load: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { duration: '2m', target: 50 }, // ramp up
        { duration: '5m', target: 50 }, // hold
        { duration: '1m', target: 0 }, // ramp down
      ],
      gracefulRampDown: '30s',
    },
  },

  thresholds: {
    http_req_duration: ['p(95)<500'],
    http_req_failed: ['rate<0.01'],
  },
};

export default function () {
  const res = http.get(`${BASE_URL}/api/quotes`);
  check(res, {
    'status 200': (r) => r.status === 200,
    'has quotes': (r) => r.json('quotes') != null, // loose != also catches undefined
  });
  sleep(1);
}
