// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * k6 executors and load patterns example
 *
 * Covers all 7 executors with realistic configuration examples.
 * Pick the relevant scenario block and remove the others.
 *
 * Executors:
 *   constant-vus          — fixed VU count for a duration
 *   ramping-vus           — variable VU count (realistic traffic curves)
 *   constant-arrival-rate — fixed iteration rate (RPS), regardless of response time
 *   ramping-arrival-rate  — variable RPS over time
 *   per-vu-iterations     — each VU runs N iterations exactly
 *   shared-iterations     — total iteration budget shared across VUs
 *   externally-controlled — VU count controlled at runtime via k6 REST API
 */
import http from 'k6/http';
import { check, sleep } from 'k6';

const BASE_URL = 'https://quickpizza.grafana.com';

// ── Choose ONE scenario block for your script ────────────────────────────────

export const options = {
  // ── 1. constant-vus: steady load for a fixed duration ──────────────────
  // scenarios: {
  //   steady: { executor: 'constant-vus', vus: 10, duration: '30s' },
  // },

  // ── 2. ramping-vus: dinner-time peak for a takeaway site ───────────────
  scenarios: {
    dinner_rush: {
      executor: 'ramping-vus',
      startVUs: 0,
      stages: [
        { duration: '10m', target: 20 }, // 5–6pm: background traffic
        { duration: '15m', target: 80 }, // 6–7pm: building
        { duration: '30m', target: 150 }, // 7–8pm: dinner peak
        { duration: '15m', target: 40 }, // 8–9pm: tapering
        { duration: '10m', target: 0 }, // 9pm: quiet
      ],
      gracefulRampDown: '2m',
    },
  },

  // ── 3. constant-arrival-rate: fixed RPS (e.g. 30 orders/sec) ──────────
  // scenarios: {
  //   steady_orders: {
  //     executor: 'constant-arrival-rate',
  //     rate: 30,
  //     timeUnit: '1s',        // 30 iterations per second
  //     duration: '5m',
  //     preAllocatedVUs: 50,   // initial VU pool
  //     maxVUs: 200,           // hard cap
  //   },
  // },

  // ── 4. ramping-arrival-rate: variable RPS ─────────────────────────────
  // scenarios: {
  //   lunch_ramp: {
  //     executor: 'ramping-arrival-rate',
  //     startRate: 5,
  //     timeUnit: '1s',
  //     stages: [
  //       { duration: '3m', target: 50 },
  //       { duration: '5m', target: 50 },
  //       { duration: '2m', target: 0  },
  //     ],
  //     preAllocatedVUs: 30,
  //     maxVUs: 150,
  //   },
  // },

  // ── 5. per-vu-iterations: each VU completes a full user journey ────────
  // scenarios: {
  //   user_journey: {
  //     executor: 'per-vu-iterations',
  //     vus: 10,
  //     iterations: 5,     // each VU runs exactly 5 times
  //     maxDuration: '5m',
  //   },
  // },

  // ── 6. shared-iterations: fixed total budget shared across VUs ─────────
  // scenarios: {
  //   smoke: {
  //     executor: 'shared-iterations',
  //     vus: 5,
  //     iterations: 50,
  //     maxDuration: '2m',
  //   },
  // },

  // ── 7. externally-controlled: VU count set via k6 REST API ─────────────
  // scenarios: {
  //   dynamic: {
  //     executor: 'externally-controlled',
  //     vus: 10,
  //     maxVUs: 100,
  //     duration: '10m',
  //   },
  // },

  thresholds: {
    http_req_duration: ['p(95)<1000'],
    http_req_failed: ['rate<0.02'],
  },
};

export default function () {
  const res = http.get(`${BASE_URL}/api/quotes`);
  check(res, { 'status 200': (r) => r.status === 200 });
  sleep(1);
}
