// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * xk6-faker — fake data generation
 *
 * Build: xk6 build --with github.com/grafana/xk6-faker@latest -o ./k6-with-faker
 * Run:   ./k6-with-faker run k6/scripts/faker-test.js
 */
import { Faker } from 'k6/x/faker';
import http from 'k6/http';
import { check, sleep } from 'k6';

// Seeded for reproducibility. Change seed to get different (but stable) data.
const fake = new Faker(42);

export const options = {
  vus: 5,
  duration: '20s',
  thresholds: {
    http_req_duration: ['p(95)<1000'],
    checks: ['rate>0.95'],
  },
};

export default function () {
  // Generate a unique username by appending VU+timestamp to the fake name
  const username = `${fake.internet.username()}_${__VU}_${Date.now()}`;
  const user = {
    username,
    password: 'pass123',
    name: `${fake.person.firstName()} ${fake.person.lastName()}`,
    email: fake.internet.email(),
  };

  const res = http.post(
    'https://quickpizza.grafana.com/api/users',
    JSON.stringify({ username: user.username, password: user.password }),
    { headers: { 'Content-Type': 'application/json' } }
  );

  check(res, {
    'registered 201': (r) => r.status === 201,
  });

  console.log(`VU ${__VU} registered: ${user.username} (${user.name})`);
  sleep(1);
}
