// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * xk6-exec — run external shell commands from k6 scripts
 *
 * Build: xk6 build --with github.com/grafana/xk6-exec@latest -o ./k6-with-exec
 * Run:   ./k6-with-exec run k6/scripts/exec-test.js
 *
 * Use cases: health-check scripts, data setup, calling CLIs.
 * exec.command(cmd, args) blocks until the command completes and returns stdout.
 */
import exec from 'k6/x/exec';
import http from 'k6/http';
import { check } from 'k6';

export const options = {
  vus: 1,
  iterations: 3,
};

export function setup() {
  // Run a setup command before the test
  const out = exec.command('echo', ['k6 exec test starting']);
  console.log('setup:', out.trim());
}

export default function () {
  // Run a command and use its output
  const timestamp = exec.command('date', ['+%s']).trim();

  const res = http.get(`https://quickpizza.grafana.com/api/quotes`);
  check(res, { 'status 200': (r) => r.status === 200 });

  console.log(`[${timestamp}] VU ${__VU}: status=${res.status}`);
}
