// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * xk6-redis — Redis client
 *
 * Build: xk6 build --with github.com/grafana/xk6-redis@latest -o ./k6-with-redis
 * Run:   ./k6-with-redis run k6/scripts/redis-test.js
 *
 * IMPORTANT API NOTES:
 * - Constructor takes a URL string: new redis.Client('redis://localhost:6379')
 *   Do NOT pass an options object — that will throw.
 * - All methods are async — use await.
 * - client.get() throws 'redis: nil' when the key does not exist.
 *   Wrap in try/catch and check e.message for 'redis: nil' to handle cache misses.
 */
import redis from 'k6/x/redis';
import { Counter } from 'k6/metrics';
import http from 'k6/http';
import { check, sleep } from 'k6';

const client = new redis.Client('redis://localhost:6379');
const cacheHits = new Counter('cache_hits');

export const options = {
  vus: 5,
  duration: '30s',
  thresholds: {
    http_req_duration: ['p(95)<2000'],
    checks: ['rate>0.95'],
    // cache_hits threshold only meaningful across multiple iterations
    // cache_hits: ['count>0'],
  },
};

export default async function () {
  const cacheKey = 'quickpizza:quotes';
  let body;

  try {
    // Cache hit path — get() throws 'redis: nil' on miss
    body = await client.get(cacheKey);
    cacheHits.add(1);
    console.log('cache hit');
  } catch (e) {
    if (e.message && e.message.includes('redis: nil')) {
      // Cache miss — fetch from API and store with 30s TTL
      const res = http.get('https://quickpizza.grafana.com/api/quotes');
      check(res, { 'api 200': (r) => r.status === 200 });
      body = res.body;
      await client.set(cacheKey, body, 30);
      console.log('cache miss, stored');
    } else {
      throw e; // unexpected Redis error
    }
  }

  check(body, { 'got value': (b) => b != null && b.length > 0 });
  sleep(1);
}
