// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * xk6-crawler — web crawling
 *
 * Build: xk6 build --with github.com/grafana/xk6-crawler@latest -o ./k6-with-crawler
 * Run:   ./k6-with-crawler run k6/scripts/crawler-test.js
 *
 * crawler.crawl(url) fetches the page and extracts the title and all links.
 * Returns: { title: string, links: string[] }
 * It is async — use await.
 */
import { Crawler } from 'k6/x/crawler';
import { check } from 'k6';

export const options = {
  vus: 1,
  iterations: 1,
  thresholds: {
    checks: ['rate==1'],
  },
};

export default async function () {
  const crawler = new Crawler();
  const result = await crawler.crawl('https://quickpizza.grafana.com');

  check(result, {
    'has title': (r) => r.title && r.title.length > 0,
    'has links': (r) => r.links && r.links.length > 0,
    'title not empty': (r) => r.title.trim() !== '',
  });

  console.log(`Title: "${result.title}" | Links found: ${result.links.length}`);
  // Log first few links
  result.links.slice(0, 3).forEach((link) => console.log(' -', link));
}
