// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * xk6-sql + sqlite3 driver — SQL database client
 *
 * Build: CGO_ENABLED=1 xk6 build \
 *          --with github.com/grafana/xk6-sql@latest \
 *          --with github.com/grafana/xk6-sql-driver-sqlite3@latest \
 *          -o ./k6-with-sql
 * Run:   ./k6-with-sql run k6/scripts/sql-test.js
 *
 * For other databases, replace the driver import:
 *   postgres: 'k6/x/sql/driver/postgres'
 *   mysql:    'k6/x/sql/driver/mysql'
 *
 * IMPORTANT API NOTES:
 * - db.query() returns a plain JavaScript ARRAY of row objects.
 *   NOT a ResultSet with .next() — that does not exist.
 *   Access rows like: rows[0].column_name
 * - db.exec(query, ...args) uses positional ? placeholders.
 * - SQLite requires CGO_ENABLED=1 at build time.
 */
import sql from 'k6/x/sql';
import driver from 'k6/x/sql/driver/sqlite3';
import http from 'k6/http';
import { check, sleep } from 'k6';

const db = sql.open(driver, '/tmp/k6_results.db');

export const options = {
  vus: 3,
  duration: '20s',
  thresholds: {
    http_req_duration: ['p(95)<1000'],
    checks: ['rate>0.95'],
  },
};

export function setup() {
  // Drop and recreate for a clean run
  db.exec('DROP TABLE IF EXISTS results');
  db.exec(`CREATE TABLE results (
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    endpoint TEXT,
    status   INTEGER,
    duration REAL,
    ts       TEXT
  )`);
}

export default function () {
  const res = http.get('https://quickpizza.grafana.com/api/quotes');

  db.exec(
    'INSERT INTO results (endpoint, status, duration, ts) VALUES (?, ?, ?, ?)',
    '/api/quotes',
    res.status,
    res.timings.duration,
    new Date().toISOString()
  );

  check(res, { 'status 200': (r) => r.status === 200 });
  sleep(1);
}

export function teardown() {
  // db.query() returns a plain array — access rows[0].column_name
  const rows = db.query('SELECT count(*) as cnt FROM results');
  console.log(`Total results recorded: ${rows[0].cnt}`);

  const slowRows = db.query('SELECT endpoint, duration FROM results WHERE duration > 500');
  if (slowRows.length > 0) {
    console.log(`Slow requests (>500ms): ${slowRows.length}`);
  }
}
