// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * xk6-tcp — raw TCP connections
 *
 * Build: xk6 build --with github.com/grafana/xk6-tcp@latest -o ./k6-with-tcp
 * Run:   ./k6-with-tcp run k6/scripts/tcp-test.js
 *
 * IMPORTANT API NOTES:
 * - open() does NOT exist — use new tcp.Socket()
 * - The API mirrors Node.js net.Socket: event-driven with socket.on(event, handler)
 * - socket.connect(port, host) — note port FIRST, then host (not a URL string)
 * - socket.destroy() closes the connection
 * - Must be async — use await with a Promise that resolves on the 'close' event
 *
 * Events: 'connect', 'data', 'close', 'error', 'timeout'
 */
import tcp from 'k6/x/tcp';
import { check } from 'k6';

export const options = {
  scenarios: {
    tcp_check: {
      executor: 'shared-iterations',
      vus: 1,
      iterations: 1,
    },
  },
  thresholds: {
    checks: ['rate==1'],
  },
};

export default async function () {
  const socket = new tcp.Socket();
  let connected = false;

  socket.on('connect', () => {
    connected = true;
    console.log('TCP connected to quickpizza.grafana.com:443');
    socket.destroy(); // close immediately — we only need to verify connectivity
  });

  socket.on('error', (err) => {
    console.error('TCP error:', err);
  });

  // Wait for the connection lifecycle to complete before the function returns
  await new Promise((resolve) => {
    socket.on('close', resolve);
    // connect(port, host) — port first
    socket.connect(443, 'quickpizza.grafana.com');
  });

  check(connected, {
    'tcp connected': (v) => v === true,
  });
}
