// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * xk6-tls — TLS certificate inspection
 *
 * Build: xk6 build --with github.com/grafana/xk6-tls@latest -o ./k6-with-tls
 * Run:   ./k6-with-tls run k6/scripts/tls-test.js
 *
 * IMPORTANT API NOTES:
 * - getCertificate(host) — async, takes the hostname ONLY (no port argument).
 * - cert.expires is a millisecond timestamp — compare with Date.now(), not new Date().
 *   Do NOT use cert.notAfter — that property does not exist.
 */
import tls from 'k6/x/tls';
import { check } from 'k6';

export const options = {
  scenarios: {
    tls_check: {
      executor: 'shared-iterations',
      vus: 1,
      iterations: 1,
    },
  },
  thresholds: {
    checks: ['rate==1'],
  },
};

export default async function () {
  const host = 'quickpizza.grafana.com';

  // No port argument — just the hostname
  const cert = await tls.getCertificate(host);

  check(cert, {
    'cert not expired': (c) => c.expires > Date.now(),
    'cert expires > 7 days': (c) => c.expires > Date.now() + 7 * 24 * 60 * 60 * 1000,
  });

  const expiresAt = new Date(cert.expires).toISOString();
  console.log(`${host} TLS cert expires: ${expiresAt}`);
}
