// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * xk6-dns — DNS resolution
 *
 * Build: xk6 build --with github.com/grafana/xk6-dns@latest -o ./k6-with-dns
 * Run:   ./k6-with-dns run k6/scripts/dns-test.js
 *
 * Two methods — both return Promise<string[]> (array of IP addresses):
 *
 *   dns.lookup(host)
 *     Uses the system's default DNS resolver. Simplest option — no nameserver needed.
 *
 *   dns.resolve(host, recordType, nameserver)
 *     Uses a specific DNS server (e.g. '8.8.8.8:53'). recordType: 'A', 'AAAA', 'CNAME', etc.
 *
 * Both are async — use await.
 */
import dns from 'k6/x/dns';
import { check } from 'k6';

export const options = {
  scenarios: {
    dns_check: {
      executor: 'shared-iterations',
      vus: 1,
      iterations: 1,
    },
  },
  thresholds: {
    checks: ['rate==1'],
  },
};

export default async function () {
  const host = 'quickpizza.grafana.com';

  // System DNS lookup (simplest)
  const ips = await dns.lookup(host);
  check(ips, {
    'lookup resolved': (r) => r !== null && r.length > 0,
  });
  console.log(`${host} system DNS: ${JSON.stringify(ips)}`);

  // Custom nameserver lookup
  const ips2 = await dns.resolve(host, 'A', '8.8.8.8:53');
  check(ips2, {
    'resolve via 8.8.8.8': (r) => r !== null && r.length > 0,
  });
  console.log(`${host} via 8.8.8.8: ${JSON.stringify(ips2)}`);
}
