// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * k6 functional test example — k6-testing library
 *
 * Covers: expect() for HTTP assertions, expect(page/locator) for browser
 *         with automatic retry, multi-scenario script with named exec functions,
 *         HTTP + browser in the same script
 *
 * Use this pattern for functional/integration tests instead of check().
 * expect() on browser locators/pages automatically retries until timeout.
 *
 * Key matchers:
 *   HTTP values (instant): toEqual, toBe, toContain, toBeDefined, toBeTruthy,
 *                          toBeGreaterThan, toBeLessThan, toHaveLength, toHaveProperty
 *   Browser (retrying):    toBeVisible, toBeHidden, toBeEnabled, toBeChecked,
 *                          toHaveText, toContainText, toHaveAttribute, toHaveValue,
 *                          toHaveTitle (on page objects)
 *   Non-throwing:          expect.soft(value).toEqual(...) — collects all failures
 *
 * LOCATOR ACTIONABILITY:
 *   - Do NOT call waitFor() before interacting (click, fill, select). Locators
 *     automatically wait for visibility, enabled state, and stability.
 *   - Only use waitFor() when asserting an element state WITHOUT interacting with it.
 *   - Do NOT use waitForLoadState(). Interact directly with the next element you
 *     expect — actionability checks handle the waiting.
 */
import { expect } from 'https://jslib.k6.io/k6-testing/0.6.1/index.js';
import { browser } from 'k6/browser';
import http from 'k6/http';

const BASE_URL = 'https://quickpizza.grafana.com';

export const options = {
  scenarios: {
    http_functional: {
      executor: 'shared-iterations',
      vus: 1,
      iterations: 1,
      exec: 'httpTest',
    },
    browser_functional: {
      executor: 'shared-iterations',
      vus: 1,
      iterations: 1,
      exec: 'browserTest',
      options: {
        browser: { type: 'chromium' },
      },
    },
  },
};

// ── HTTP functional test ──────────────────────────────────────────────────────
export function httpTest() {
  const res = http.get(`${BASE_URL}/api/quotes`);

  // Instant assertions (no retry)
  expect(res.status).toEqual(200);
  expect(res.json('quotes')).toBeDefined();
  expect(res.timings.duration).toBeLessThan(2000);

  // Soft assertions — collects all failures instead of throwing on first
  expect.soft(res.headers['Content-Type']).toContain('application/json');
}

// ── Browser functional test ───────────────────────────────────────────────────
export async function browserTest() {
  const page = await browser.newPage();

  try {
    // Navigate — no waitForLoadState(). Interact directly with elements
    // on the new page; actionability checks handle the waiting.
    await page.goto(BASE_URL);

    // Page-level retrying assertion (not an interaction — waitFor is via expect)
    await expect(page).toHaveTitle(/QuickPizza/);

    // Click directly — no waitFor() needed before interacting with a locator.
    // getByRole automatically waits for the button to be visible and enabled.
    await page.getByRole('button', { name: 'Pizza, Please!' }).click();

    // Assert the result appeared (not interacting — waitFor via expect is correct)
    await expect(page.getByText('Our recommendation:')).toBeVisible();
  } finally {
    await page.close();
  }
}
