// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * k6 gRPC example — k6/net/grpc
 *
 * Covers: Client, load(), connect(), invoke(), StatusOK, close() in finally,
 *         plaintext and TLS connections, thresholds, check()
 *
 * IMPORTANT: client.load() paths are resolved relative to the SCRIPT FILE
 * location, not the working directory. Place the .proto file next to the
 * script, or adjust the path accordingly.
 *
 * For servers with gRPC reflection: use client.load(null) and connect
 * with { reflect: true } instead of providing a proto file.
 */
import { Client, StatusOK } from 'k6/net/grpc';
import { check, sleep } from 'k6';

// Load proto relative to this script file's location
const client = new Client();
client.load(['./proto'], 'quickpizza.proto');
// Reflection alternative: client.load(null);

const GRPC_ADDR = 'localhost:3334'; // plaintext
// const GRPC_ADDR = 'api.example.com:443'; // TLS (remove plaintext: true below)

export const options = {
  vus: 3,
  duration: '20s',
  thresholds: {
    grpc_req_duration: ['p(95)<500'],
    checks: ['rate>0.99'],
  },
};

export default function () {
  // Connect (with plaintext for local/dev servers without TLS)
  client.connect(GRPC_ADDR, { plaintext: true });
  // TLS: client.connect(GRPC_ADDR);

  try {
    // ── Unary call: Status check ────────────────────────────────────────────
    const statusRes = client.invoke('quickpizza.GRPC/Status', {});
    check(statusRes, {
      'status ok': (r) => r && r.status === StatusOK,
      'service ready': (r) => r && r.message && r.message.ready === true,
    });

    // ── Unary call: RatePizza ───────────────────────────────────────────────
    const ratingRes = client.invoke('quickpizza.GRPC/RatePizza', {
      ingredients: ['Pepperoni', 'Mozzarella'],
      dough: 'Traditional',
    });
    check(ratingRes, {
      'rating ok': (r) => r && r.status === StatusOK,
      'stars in range': (r) =>
        r && r.message && r.message.starsRating >= 1 && r.message.starsRating <= 5,
    });
  } finally {
    // Release the connection even if invoke() or a check throws mid-iteration.
    client.close();
  }

  sleep(1);
}
