// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * k6 HTML parsing + SharedArray example — k6/html + k6/data
 *
 * Covers: parseHTML(), jQuery-style selectors (.find, .text, .size, .toArray),
 *         SharedArray (inline array, loaded once at init time)
 *
 * IMPORTANT: QuickPizza's root URL (/) is a SvelteKit SPA.
 * Its server-rendered HTML shell contains NO <button>, <form>, or visible
 * content — those are injected by JavaScript at runtime, which k6's HTTP
 * client does not execute. Use /login or API endpoints when testing with
 * parseHTML, as those pages have server-rendered content.
 */
import { parseHTML } from 'k6/html';
import { SharedArray } from 'k6/data';
import http from 'k6/http';
import { check, sleep } from 'k6';

const BASE_URL = 'https://quickpizza.grafana.com';

// SharedArray: loaded ONCE at init time, shared read-only across all VUs.
// Replace with JSON.parse(open('./endpoints.json')) to load from a file.
const endpoints = new SharedArray('endpoints', () => [
  '/api/quotes',
  '/api/names',
  '/api/adjectives',
]);

export const options = {
  vus: 5,
  duration: '30s',
  thresholds: {
    http_req_duration: ['p(95)<500'],
    checks: ['rate>0.95'],
  },
};

export default function () {
  // ── Pick endpoint via SharedArray ─────────────────────────────────────────
  const path = endpoints[__VU % endpoints.length];
  const apiRes = http.get(`${BASE_URL}${path}`);
  check(apiRes, { 'api status 200': (r) => r.status === 200 });

  // ── HTML parsing — use /login, NOT / (which is a JS SPA) ──────────────────
  const htmlRes = http.get(`${BASE_URL}/login`);
  const doc = parseHTML(htmlRes.body);

  check(doc, {
    'has button': (d) => d.find('button').size() > 0,
    'has heading': (d) => d.find('h1').size() > 0,
  });

  // Extract text content
  const heading = doc.find('h1').text();
  const buttons = doc
    .find('button')
    .toArray()
    .map((el) => el.text().trim());
  console.log(
    `VU ${__VU} | endpoint=${path} | heading="${heading}" | buttons=${buttons.join(',')}`
  );

  sleep(1);
}
