// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * k6 HTTP example — load test + authenticated flow
 *
 * Covers: http.get/post/batch, check(), sleep(), thresholds,
 *         auth token flow, JSON body, SharedArray
 *
 * Adapt BASE_URL, endpoints, and credentials to your target.
 * Keep it lean: add per-request tags ({ tags: { endpoint: 'x' } }) or extra
 * sleep() calls only when the user asks for them.
 */
import http from 'k6/http';
import { check, sleep, fail } from 'k6';
import { SharedArray } from 'k6/data';

const BASE_URL = 'https://quickpizza.grafana.com';

// SharedArray is loaded once at init time and shared across all VUs (read-only).
const users = new SharedArray('users', () => [
  { username: 'alice', password: 'pass1' },
  { username: 'bob', password: 'pass2' },
]);

export const options = {
  vus: 10,
  duration: '30s',
  thresholds: {
    http_req_duration: ['p(95)<500', 'p(99)<1000'],
    http_req_failed: ['rate<0.01'],
    checks: ['rate>0.99'],
  },
};

export default function () {
  // ── Simple GET ────────────────────────────────────────────────────────────
  const quotesRes = http.get(`${BASE_URL}/api/quotes`);
  check(quotesRes, {
    'quotes status 200': (r) => r.status === 200,
    'quotes has body': (r) => r.body.length > 0,
  });

  // ── Authenticated flow ────────────────────────────────────────────────────
  // Step 1: register a unique user
  const username = `user_${__VU}_${Date.now()}`;
  const password = 'password123';

  const registerRes = http.post(`${BASE_URL}/api/users`, JSON.stringify({ username, password }), {
    headers: { 'Content-Type': 'application/json' },
  });
  check(registerRes, { 'register 201': (r) => r.status === 201 });

  // Step 2: login for a token
  const loginRes = http.post(
    `${BASE_URL}/api/users/token/login`,
    JSON.stringify({ username, password }),
    { headers: { 'Content-Type': 'application/json' } }
  );
  const loginOk = check(loginRes, {
    'login 200': (r) => r.status === 200,
    'has token': (r) => r.json('token') != null, // loose != also catches undefined
  });
  if (!loginOk) {
    fail('login failed');
  }
  const token = loginRes.json('token');

  // Step 3: authenticated request
  const authHeaders = {
    Authorization: `Token ${token}`,
    'Content-Type': 'application/json',
  };

  // Send an explicit empty JSON object — the API rejects a literal null body.
  const pizzaRes = http.post(`${BASE_URL}/api/pizza`, JSON.stringify({}), {
    headers: authHeaders,
  });
  const pizzaOk = check(pizzaRes, {
    'pizza 200': (r) => r.status === 200,
    'has pizza': (r) => r.json('pizza') != null, // loose != also catches undefined
  });

  // Step 4: use data from the previous response
  if (pizzaOk) {
    const pizzaId = pizzaRes.json('pizza.id');
    const ratingRes = http.post(
      `${BASE_URL}/api/ratings`,
      JSON.stringify({ stars: 5, pizza_id: pizzaId }),
      { headers: authHeaders }
    );
    check(ratingRes, { 'rating 201': (r) => r.status === 201 });
  }

  // ── Batch requests ────────────────────────────────────────────────────────
  const [r1, r2] = http.batch([
    ['GET', `${BASE_URL}/api/quotes`],
    ['GET', `${BASE_URL}/api/names`],
  ]);
  check(r1, { 'batch quotes 200': (r) => r.status === 200 });
  check(r2, { 'batch names 200': (r) => r.status === 200 });

  sleep(1);
}
