// Generated by grafana-k6 on {{GENERATED_AT}}
/**
 * k6 metrics, data, and lifecycle example
 *
 * Covers: Counter, Gauge, Rate, Trend (custom metrics),
 *         SharedArray (shared test data, loaded once),
 *         execution module (VU/scenario runtime info),
 *         per-vu-iterations executor,
 *         setup() / teardown() / handleSummary()
 *
 * Notes:
 * - SharedArray initialiser runs once at init time — keep it cheap.
 * - execution.vu.idInTest is 1-indexed and unique per VU across all scenarios.
 * - handleSummary receives the same data object as the built-in summary.
 * - textSummary comes from the k6-summary jslib (imported below); it is NOT a global.
 */
import http from 'k6/http';
import { check, sleep } from 'k6';
import { Counter, Gauge, Rate, Trend } from 'k6/metrics';
import { SharedArray } from 'k6/data';
import execution from 'k6/execution';
import { textSummary } from 'https://jslib.k6.io/k6-summary/0.1.0/index.js';

// ── Custom metrics ─────────────────────────────────────────────────────────
const requestCount = new Counter('pizza_requests'); // cumulative count
const activeVUs = new Gauge('active_vus'); // current value
const successRate = new Rate('pizza_success_rate'); // 0–1 ratio
const requestTrend = new Trend('pizza_req_duration_ms', true); // distribution

// ── Shared test data ───────────────────────────────────────────────────────
// Inline array — replace JSON.parse(open('./data.json')) for external files.
const ingredients = new SharedArray('ingredients', () => [
  'Pepperoni',
  'Mozzarella',
  'Mushrooms',
  'Olives',
  'Basil',
]);

export const options = {
  scenarios: {
    user_journey: {
      executor: 'per-vu-iterations',
      vus: 5,
      iterations: 3, // each VU runs exactly 3 iterations
      maxDuration: '5m',
    },
  },
  thresholds: {
    pizza_success_rate: ['rate>0.95'],
    pizza_req_duration_ms: ['p(95)<1000', 'avg<500'],
    pizza_requests: ['count>0'],
  },
};

export function setup() {
  // Runs once before all VUs start. Return value is passed to default + teardown.
  const health = http.get('https://quickpizza.grafana.com/api/quotes');
  if (health.status !== 200) {
    throw new Error(`Service not healthy: ${health.status}`);
  }
  return { baseUrl: 'https://quickpizza.grafana.com', startedAt: Date.now() };
}

export default function (data) {
  // execution gives runtime context
  const vuId = execution.vu.idInTest;
  const scenarioIter = execution.scenario.iterationInInstance;

  // Pick an ingredient based on VU ID (deterministic)
  const ingredient = ingredients[vuId % ingredients.length];

  activeVUs.add(1);

  const start = Date.now();
  const res = http.get(`${data.baseUrl}/api/quotes`, {
    tags: { vu_id: String(vuId), iteration: String(scenarioIter) },
  });
  const duration = Date.now() - start;

  requestTrend.add(duration);
  requestCount.add(1);

  const ok = check(res, {
    'status 200': (r) => r.status === 200,
    'has quotes': (r) => r.json('quotes') !== undefined,
  });
  successRate.add(ok);

  console.log(`VU ${vuId} iter ${scenarioIter} | ${ingredient} | ${duration}ms | ok=${ok}`);

  activeVUs.add(-1);
  sleep(1);
}

export function teardown(data) {
  const elapsed = ((Date.now() - data.startedAt) / 1000).toFixed(1);
  console.log(`Test finished. Elapsed: ${elapsed}s`);
}

export function handleSummary(data) {
  // Return a custom summary. textSummary is imported from the k6-summary jslib above.
  return {
    'k6-summary.json': JSON.stringify(data, null, 2),
    stdout: textSummary(data, { indent: '  ', enableColors: true }),
  };
}
