# infra/k8s/helm-values/postgres.yaml
auth:
  username: vp
  password: vp
  database: vp
  postgresPassword: vp

primary:
  persistence:
    enabled: true
    size: 5Gi
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
