export const PipelineErrorCodes = {
  UNSUPPORTED_CODEC: 'UNSUPPORTED_CODEC',
  CORRUPT_CONTAINER: 'CORRUPT_CONTAINER',
  DURATION_EXCEEDED: 'DURATION_EXCEEDED',
  SOURCE_MISSING: 'SOURCE_MISSING',
  FFMPEG_FAILED: 'FFMPEG_FAILED',
  FFMPEG_OOM: 'FFMPEG_OOM',
  FFMPEG_TIMEOUT: 'FFMPEG_TIMEOUT',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE',
  SEGMENT_VERIFY_FAILED: 'SEGMENT_VERIFY_FAILED',
  DISK_FULL: 'DISK_FULL',
} as const;

export type PipelineErrorCode = (typeof PipelineErrorCodes)[keyof typeof PipelineErrorCodes];
