import { inProcessAppConfig } from '@vp/env-schema';
import { dump } from 'js-yaml';
import { composeApp } from '../app';

export const OPENAPI_DOCUMENT_FILE = 'packages/universal/api-contracts/openapi.yaml';

const HEADER = '# Generated by `pnpm gen:contracts`. Do not edit.\n';

/**
 * The document `/openapi.json` serves, as YAML. It is rendered from the in-process (dev-auth)
 * configuration, the only one that mounts every contract endpoint, the dev JWKS included.
 */
export async function renderOpenApiDocument(): Promise<string> {
  const { app } = await composeApp({ config: inProcessAppConfig() });
  await app.ready();
  const document = app.swagger();
  await app.close();
  return `${HEADER}${dump(document, { lineWidth: -1, noRefs: true })}`;
}
