/**
 * Sources that still `catch` outside the boundary that converts a throw into a `Result`, as of
 * the commit that made ADR-24 machine-enforced. The list may only shrink:
 * `catch-confinement.test.ts` fails both on a new breach and on a listed entry that no longer
 * catches, so it can never be appended to.
 */

export const LEGACY_CATCH_SITES: readonly string[] = [
  'apps/api/src/migrate.ts',
  'apps/api/src/plugins/auth.ts',
  'apps/api/src/plugins/jwks-verifier.ts',
  'apps/api/src/plugins/metrics.ts',
  'apps/api/src/routes/admin/queues.ts',
  'apps/api/src/routes/health.ts',
  'apps/api/src/services/channel-service.ts',
  'apps/api/src/services/cursor.ts',
  'apps/api/src/services/feed-service.ts',
  'apps/api/src/services/queue-poller.ts',
  'apps/api/src/services/sql-poller.ts',
  'apps/api/src/services/sse-connection.ts',
  'apps/api/src/services/sse-hub.ts',
  'apps/api/src/services/upload-complete.ts',
  'apps/web/src/auth-token.ts',
  'apps/web/src/base-api.ts',
  'apps/web/src/modules/shared/providers/permissions-provider.tsx',
  'apps/worker/src/failure-handler.ts',
  'apps/worker/src/main.ts',
  'apps/worker/src/stages/housekeeping/outbox-relay.ts',
  'apps/worker/src/stages/housekeeping/purge-deleted.ts',
  'apps/worker/src/stages/housekeeping/reconcile-processing.ts',
  'apps/worker/src/stages/housekeeping/reconcile-uploads.ts',
  'apps/worker/src/stages/housekeeping/tmp-sweep.ts',
  'apps/worker/src/stages/notify.ts',
  'apps/worker/src/stages/package.ts',
  'apps/worker/src/stages/probe.ts',
  'apps/worker/src/stages/progress-reporter.ts',
  'apps/worker/src/stages/segment-uploader.ts',
  'apps/worker/src/stages/thumbnail.ts',
  'apps/worker/src/stages/transcode.ts',
  'apps/worker/src/with-telemetry.ts',
  'packages/server/compose-autoscaler/src/cli.ts',
  'packages/server/compose-autoscaler/src/runner.ts',
  'packages/server/db/src/migrate.ts',
  'packages/server/db/src/seed.ts',
  'packages/server/dev-token/src/index.ts',
  'packages/server/ffmpeg/src/probe.ts',
  'packages/server/ffmpeg/src/transcode.ts',
  'packages/server/gen-video/src/generator.ts',
  'packages/server/gen-video/src/probe.ts',
  'packages/server/observability/src/server.ts',
  'packages/server/observability/src/tracing.ts',
  'packages/server/storage/src/keys.ts',
  'packages/server/upload-client/src/client.ts',
  'packages/universal/api-contracts/src/videos.ts',
  'packages/universal/pagination/src/cursor-codec.ts',
  'scripts/check-boundaries.ts',
  'scripts/sync-claude-symlinks.ts',
];
