/**
 * Production sources without the sibling `__tests__/<name>.test.ts` Rule 12 mandates,
 * as of the commit that made Rule 12 machine-enforced. The list may only shrink:
 * `test-correspondence.test.ts` fails both on an uncovered source that is not listed,
 * and on a listed source that has since gained its spec.
 */
export const UNTESTED_SOURCES: readonly string[] = [
  'packages/server/adapters/in-memory/in-memory-cache-client.ts',
  'packages/server/adapters/in-memory/in-memory-database-client.ts',
  'packages/server/adapters/in-memory/in-memory-flow-producer.ts',
  'packages/server/adapters/in-memory/in-memory-job-queue.ts',
  'packages/server/adapters/in-memory/in-memory-multipart-storage.ts',
  'packages/server/adapters/in-memory/in-memory-storage-client.ts',
  'packages/server/adapters/in-memory/repositories/in-memory-category-repository.ts',
  'packages/server/adapters/in-memory/repositories/in-memory-channel-repository.ts',
  'packages/server/adapters/in-memory/repositories/in-memory-dlq-repository.ts',
  'packages/server/adapters/in-memory/repositories/in-memory-event-repository.ts',
  'packages/server/adapters/in-memory/repositories/in-memory-outbox-repository.ts',
  'packages/server/adapters/in-memory/repositories/in-memory-rendition-repository.ts',
  'packages/server/adapters/in-memory/repositories/in-memory-step-repository.ts',
  'packages/server/adapters/in-memory/repositories/in-memory-upload-repository.ts',
  'packages/server/adapters/in-memory/repositories/in-memory-user-repository.ts',
  'packages/server/adapters/in-memory/repositories/in-memory-video-reaction-repository.ts',
  'packages/server/adapters/in-memory/repositories/in-memory-video-repository.ts',
  'packages/server/adapters/in-memory/repositories/types.ts',
  'packages/server/adapters/postgres/repositories/postgres-category-repository.ts',
  'packages/server/adapters/postgres/repositories/postgres-channel-repository.ts',
  'packages/server/adapters/postgres/repositories/postgres-dlq-repository.ts',
  'packages/server/adapters/postgres/repositories/postgres-event-repository.ts',
  'packages/server/adapters/postgres/repositories/postgres-outbox-repository.ts',
  'packages/server/adapters/postgres/repositories/postgres-rendition-repository.ts',
  'packages/server/adapters/postgres/repositories/postgres-step-repository.ts',
  'packages/server/adapters/postgres/repositories/postgres-subscription-repository.ts',
  'packages/server/adapters/postgres/repositories/postgres-upload-repository.ts',
  'packages/server/adapters/postgres/repositories/postgres-user-repository.ts',
  'packages/server/adapters/postgres/repositories/postgres-video-reaction-repository.ts',
  'packages/server/adapters/postgres/repositories/postgres-video-repository.ts',
  'packages/server/core/repositories/video-repository.ts',
  'packages/server/db/src/migrate.ts',
  'packages/server/db/src/seed.ts',
  'scripts/check-boundaries.ts',
  'scripts/fairness-simulation.ts',
  'scripts/run-e2e.ts',
  'scripts/sync-claude-symlinks.ts',
];
