/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as SplatRouteImport } from './routes/$';
import { Route as AuthedRouteImport } from './routes/_authed';
import { Route as TrendingRouteImport } from './routes/trending';
import { Route as ChannelChannelIdRouteImport } from './routes/channel.$channelId';
import { Route as WatchVideoIdRouteImport } from './routes/watch.$videoId';
import { Route as AuthedSubscriptionsIndexRouteImport } from './routes/_authed/subscriptions/index';
import { Route as AuthedSubscriptionsVideosRouteImport } from './routes/_authed/subscriptions/videos';
import { Route as AuthedUploadIndexRouteImport } from './routes/_authed/upload/index';
import { Route as AuthedUploadEditVideoIdRouteImport } from './routes/_authed/upload/edit.$videoId';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any);
const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any);
const ChannelChannelIdRoute = ChannelChannelIdRouteImport.update({
  id: '/channel/$channelId',
  path: '/channel/$channelId',
  getParentRoute: () => rootRouteImport,
} as any);
const WatchVideoIdRoute = WatchVideoIdRouteImport.update({
  id: '/watch/$videoId',
  path: '/watch/$videoId',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthedSubscriptionsIndexRoute =
  AuthedSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => AuthedRoute,
  } as any);
const AuthedSubscriptionsVideosRoute =
  AuthedSubscriptionsVideosRouteImport.update({
    id: '/subscriptions/videos',
    path: '/subscriptions/videos',
    getParentRoute: () => AuthedRoute,
  } as any);
const AuthedUploadIndexRoute = AuthedUploadIndexRouteImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => AuthedRoute,
} as any);
const AuthedUploadEditVideoIdRoute = AuthedUploadEditVideoIdRouteImport.update({
  id: '/upload/edit/$videoId',
  path: '/upload/edit/$videoId',
  getParentRoute: () => AuthedRoute,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/$': typeof SplatRoute;
  '/trending': typeof TrendingRoute;
  '/channel/$channelId': typeof ChannelChannelIdRoute;
  '/watch/$videoId': typeof WatchVideoIdRoute;
  '/subscriptions/videos': typeof AuthedSubscriptionsVideosRoute;
  '/subscriptions/': typeof AuthedSubscriptionsIndexRoute;
  '/upload/': typeof AuthedUploadIndexRoute;
  '/upload/edit/$videoId': typeof AuthedUploadEditVideoIdRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/$': typeof SplatRoute;
  '/trending': typeof TrendingRoute;
  '/channel/$channelId': typeof ChannelChannelIdRoute;
  '/watch/$videoId': typeof WatchVideoIdRoute;
  '/subscriptions/videos': typeof AuthedSubscriptionsVideosRoute;
  '/subscriptions': typeof AuthedSubscriptionsIndexRoute;
  '/upload': typeof AuthedUploadIndexRoute;
  '/upload/edit/$videoId': typeof AuthedUploadEditVideoIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/$': typeof SplatRoute;
  '/_authed': typeof AuthedRouteWithChildren;
  '/trending': typeof TrendingRoute;
  '/channel/$channelId': typeof ChannelChannelIdRoute;
  '/watch/$videoId': typeof WatchVideoIdRoute;
  '/_authed/subscriptions/videos': typeof AuthedSubscriptionsVideosRoute;
  '/_authed/subscriptions/': typeof AuthedSubscriptionsIndexRoute;
  '/_authed/upload/': typeof AuthedUploadIndexRoute;
  '/_authed/upload/edit/$videoId': typeof AuthedUploadEditVideoIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/$'
    | '/trending'
    | '/channel/$channelId'
    | '/watch/$videoId'
    | '/subscriptions/videos'
    | '/subscriptions/'
    | '/upload/'
    | '/upload/edit/$videoId';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/$'
    | '/trending'
    | '/channel/$channelId'
    | '/watch/$videoId'
    | '/subscriptions/videos'
    | '/subscriptions'
    | '/upload'
    | '/upload/edit/$videoId';
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authed'
    | '/trending'
    | '/channel/$channelId'
    | '/watch/$videoId'
    | '/_authed/subscriptions/videos'
    | '/_authed/subscriptions/'
    | '/_authed/upload/'
    | '/_authed/upload/edit/$videoId';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SplatRoute: typeof SplatRoute;
  AuthedRoute: typeof AuthedRouteWithChildren;
  TrendingRoute: typeof TrendingRoute;
  ChannelChannelIdRoute: typeof ChannelChannelIdRoute;
  WatchVideoIdRoute: typeof WatchVideoIdRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/$': {
      id: '/$';
      path: '/$';
      fullPath: '/$';
      preLoaderRoute: typeof SplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authed': {
      id: '/_authed';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/trending': {
      id: '/trending';
      path: '/trending';
      fullPath: '/trending';
      preLoaderRoute: typeof TrendingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/channel/$channelId': {
      id: '/channel/$channelId';
      path: '/channel/$channelId';
      fullPath: '/channel/$channelId';
      preLoaderRoute: typeof ChannelChannelIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/watch/$videoId': {
      id: '/watch/$videoId';
      path: '/watch/$videoId';
      fullPath: '/watch/$videoId';
      preLoaderRoute: typeof WatchVideoIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authed/subscriptions/': {
      id: '/_authed/subscriptions/';
      path: '/subscriptions';
      fullPath: '/subscriptions/';
      preLoaderRoute: typeof AuthedSubscriptionsIndexRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    '/_authed/subscriptions/videos': {
      id: '/_authed/subscriptions/videos';
      path: '/subscriptions/videos';
      fullPath: '/subscriptions/videos';
      preLoaderRoute: typeof AuthedSubscriptionsVideosRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    '/_authed/upload/': {
      id: '/_authed/upload/';
      path: '/upload';
      fullPath: '/upload/';
      preLoaderRoute: typeof AuthedUploadIndexRouteImport;
      parentRoute: typeof AuthedRoute;
    };
    '/_authed/upload/edit/$videoId': {
      id: '/_authed/upload/edit/$videoId';
      path: '/upload/edit/$videoId';
      fullPath: '/upload/edit/$videoId';
      preLoaderRoute: typeof AuthedUploadEditVideoIdRouteImport;
      parentRoute: typeof AuthedRoute;
    };
  }
}

interface AuthedRouteChildren {
  AuthedSubscriptionsVideosRoute: typeof AuthedSubscriptionsVideosRoute;
  AuthedSubscriptionsIndexRoute: typeof AuthedSubscriptionsIndexRoute;
  AuthedUploadIndexRoute: typeof AuthedUploadIndexRoute;
  AuthedUploadEditVideoIdRoute: typeof AuthedUploadEditVideoIdRoute;
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSubscriptionsVideosRoute: AuthedSubscriptionsVideosRoute,
  AuthedSubscriptionsIndexRoute: AuthedSubscriptionsIndexRoute,
  AuthedUploadIndexRoute: AuthedUploadIndexRoute,
  AuthedUploadEditVideoIdRoute: AuthedUploadEditVideoIdRoute,
};

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthedRoute: AuthedRouteWithChildren,
  TrendingRoute: TrendingRoute,
  ChannelChannelIdRoute: ChannelChannelIdRoute,
  WatchVideoIdRoute: WatchVideoIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
