apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vp-api
  namespace: video-pipeline
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/part-of: video-pipeline
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vp-api
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s
      scrapeTimeout: 5s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vp-workers
  namespace: video-pipeline
  labels:
    release: kube-prometheus-stack
    app.kubernetes.io/part-of: video-pipeline
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
  endpoints:
    - port: metrics
      path: /metrics
      interval: 10s
      scrapeTimeout: 5s
