import { check } from 'k6';
// Generated by grafana-k6 on 2026-09-11T16:51:00Z
import http from 'k6/http';

const API_BASE = __ENV.API || 'http://localhost:3000';

export function getAuthHeaders() {
  const token =
    __ENV.TOKEN ||
    'eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCIsImtpZCI6InZwLWRldi1rZXktMSJ9.eyJzdWIiOiIwMDAwMDAwMC0wMDAwLTcwMDAtODAwMC0wMDAwMDAwMDAwMDEiLCJyb2xlIjoidXNlciIsImlzcyI6InZwLWRldiIsImF1ZCI6InZwLWFwaSIsImlhdCI6MTc4OTE0NTQ1NiwiZXhwIjoyMTA0NTA1NDU2fQ.s309zkg-MQ6oDZHunmIfqrvyZgBETHgmuLRtcWsD_1hSZciougdfedfR2s7a2ac-oCnXmJG6TultN5c26_eeDQ';
  return {
    Authorization: `Bearer ${token}`,
    'Content-Type': 'application/json',
  };
}

export function initUpload(params) {
  const res = http.post(`${API_BASE}/v1/uploads`, JSON.stringify(params), {
    headers: getAuthHeaders(),
    tags: { name: 'presign' },
  });
  check(res, { 'init 201': (r) => r.status === 201 });
  if (res.status !== 201) {
    throw new Error(`initUpload failed: ${res.body}`);
  }
  return res.json();
}

export function completeUpload(uploadId, parts = []) {
  const res = http.post(`${API_BASE}/v1/uploads/${uploadId}/complete`, JSON.stringify({ parts }), {
    headers: getAuthHeaders(),
    tags: { name: 'complete' },
  });
  check(res, { 'complete 202': (r) => r.status === 202 });
  if (res.status !== 202) {
    throw new Error(`completeUpload failed: ${res.body}`);
  }
  return res.json();
}

export function uploadPart(url, data, partNumber) {
  const res = http.put(url, data, {
    headers: { 'Content-Type': 'video/mp4' },
    tags: { name: 'storage-put' },
  });
  check(res, { [`part ${partNumber} put 200`]: (r) => r.status === 200 });
  if (res.status !== 200) {
    throw new Error(`uploadPart ${partNumber} failed: ${res.body}`);
  }
  const etagHeader = res.headers['Etag'] || res.headers['ETag'] || `"etag-${partNumber}"`;
  return { partNumber, etag: etagHeader.replace(/^"|"$/g, '') };
}

export function getResumeInfo(uploadId) {
  const res = http.get(`${API_BASE}/v1/uploads/${uploadId}`, {
    headers: getAuthHeaders(),
    tags: { name: 'resume-info' },
  });
  check(res, { 'resume info 200': (r) => r.status === 200 });
  return res.json();
}

export function getPartUrls(uploadId, from, count = 100) {
  const res = http.post(
    `${API_BASE}/v1/uploads/${uploadId}/parts?from=${from}&count=${count}`,
    null,
    {
      headers: getAuthHeaders(),
      tags: { name: 'get-parts' },
    }
  );
  check(res, { 'get parts 200': (r) => r.status === 200 });
  return res.json().parts;
}

export function getVideo(videoId) {
  const res = http.get(`${API_BASE}/v1/videos/${videoId}`, {
    headers: getAuthHeaders(),
    tags: { name: 'get-video' },
  });
  check(res, { 'get video 200': (r) => r.status === 200 });
  return res.json();
}
