global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'job']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-webhook'

receivers:
  - name: 'default-webhook'
    webhook_configs:
      - url: 'http://localhost:5001/'
        send_resolved: true
