import { readFileSync } from 'node:fs';
import { load } from 'js-yaml';
import { buildTestApp } from '../../__tests__/test-app';
import { OPENAPI_DOCUMENT_FILE, renderOpenApiDocument } from '../openapi-document';

const REPO_ROOT = new URL('../../../../../', import.meta.url);

describe('apps/api/composition: the committed OpenAPI document', () => {
  let rendered: string;

  beforeAll(async () => {
    rendered = await renderOpenApiDocument();
  });

  it('is the document apps/api serves at /openapi.json', async () => {
    const { app } = await buildTestApp();
    const served = (await app.inject({ method: 'GET', url: '/openapi.json' })).json();
    await app.close();

    expect(load(rendered)).toEqual(served);
  });

  it('opens with a header naming the command that writes it', () => {
    expect(rendered.split('\n')[0]).toBe('# Generated by `pnpm gen:contracts`. Do not edit.');
  });

  it('is committed as rendered, so an endpoint changed without pnpm gen:contracts fails', () => {
    const committed = readFileSync(new URL(OPENAPI_DOCUMENT_FILE, REPO_ROOT), 'utf8');

    expect(committed, 'run `pnpm gen:contracts` and commit the result').toBe(rendered);
  });
});
